version: "3"
services:
  app:
    container_name: docthrive-dev
    restart: always
    build: .
    ports:
      - "3005:3005"
    command: bash -c "npm install && npm start"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    links:
      - mongo
  mongo:
    container_name: mongo-dev
    image: mongo
    command: mongod --port 27019
    ports:
      - "27019:27019"
